# Generated by Django 4.2.7 on 2023-12-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
